debug = true
checkNewVersion = true
logLevel = "INFO"
defaultEntryPoints = ["http","https"]

[entryPoints]
 [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.redirect]
    regex = "treebase.org/$"
    replacement = "treebase.org/treebase-web$1"
    [entryPoints.https.tls]
[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "treebase.org"
watch = true
exposedbydefault = false

[acme]
email = "aut@naturalis.nl"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false

[[acme.domains]]
  main = "treebase.org"
  sans = ["www.treebase.org"]

[acme.httpChallenge]
entryPoint = "http"